let n1 = 0;
let n2= 3.14;
let n3 = Infinity;
let n4 = NaN;
let n5 = true;
let n6 = 4<1;
let n7 = "texto";
let n8 = "E letra"+1994;
let n9 = Symbol("id");
let n10 = Date;
let n11 = String;
let n12 = [1,2,3,4];
let n13 = null;
let n14 = undefined; 

console.log (typeof(n1));
console.log (typeof(n2));
console.log (typeof(n3));
console.log (typeof(n4));
console.log (typeof(n5));
console.log (typeof(n6));
console.log (typeof(n7));
console.log (typeof(n8));
console.log (typeof(n9));
console.log (typeof(n10));
console.log (typeof(n11));
console.log (typeof(n12));
console.log (typeof(n13));
console.log (typeof(n14));
console.log (typeof(alert));